from marshmallow import Schema, fields, validate

class DeteccaoFraudeSchema(Schema):
    id_transacao = fields.Int(required=True, validate=validate.Range(min=1))
    amt = fields.Float(required=True, validate=validate.Range(min=0))
    category_entertainment = fields.Int(required=True, validate=validate.OneOf([0, 1]))
    category_gas_transport = fields.Int(required=True, validate=validate.OneOf([0, 1]))
    category_grocery_pos = fields.Int(required=True, validate=validate.OneOf([0, 1]))
    category_home = fields.Int(required=True, validate=validate.OneOf([0, 1]))
    category_kids_pets = fields.Int(required=True, validate=validate.OneOf([0, 1]))
    category_misc_net = fields.Int(required=True, validate=validate.OneOf([0, 1]))
    category_shopping_net = fields.Int(required=True, validate=validate.OneOf([0, 1]))
    category_shopping_pos = fields.Int(required=True, validate=validate.OneOf([0, 1]))
    category_travel = fields.Int(required=True, validate=validate.OneOf([0, 1]))
    transaction_month_1 = fields.Int(required=True, validate=validate.OneOf([0, 1]))
    transaction_month_2 = fields.Int(required=True, validate=validate.OneOf([0, 1]))
    transaction_month_3 = fields.Int(required=True, validate=validate.OneOf([0, 1]))
    transaction_month_4 = fields.Int(required=True, validate=validate.OneOf([0, 1]))
    transaction_month_5 = fields.Int(required=True, validate=validate.OneOf([0, 1]))
    transaction_month_6 = fields.Int(required=True, validate=validate.OneOf([0, 1]))
    transaction_month_7 = fields.Int(required=True, validate=validate.OneOf([0, 1]))
    transaction_month_8 = fields.Int(required=True, validate=validate.OneOf([0, 1]))
    transaction_month_9 = fields.Int(required=True, validate=validate.OneOf([0, 1]))
    transaction_month_10 = fields.Int(required=True, validate=validate.OneOf([0, 1]))
    transaction_month_11 = fields.Int(required=True, validate=validate.OneOf([0, 1]))
    transaction_month_12 = fields.Int(required=True, validate=validate.OneOf([0, 1]))
    transaction_period_Madrugada = fields.Int(required=True, validate=validate.OneOf([0, 1]))
    transaction_period_Manhã = fields.Int(required=True, validate=validate.OneOf([0, 1]))
    transaction_period_Noite = fields.Int(required=True, validate=validate.OneOf([0, 1]))
    transaction_period_Tarde = fields.Int(required=True, validate=validate.OneOf([0, 1]))