FROM tensorflow/tensorflow:2.17.0

WORKDIR /app

COPY ./src /app/src
COPY ./infra/libs /app/infra/libs
COPY swagger.yml /app/swagger.yml


RUN python -m venv /app/venv
RUN /app/venv/bin/python -m pip install -r /app/infra/libs/requirements.txt

EXPOSE 5100

ENTRYPOINT ["/app/venv/bin/python", "/app/src/app.py"]
